version: '3'
services:
    fluffy-octo-fortnight:
        image: ghcr.io/sergejkembel/fluffy-octo-fortnight:master
        ports:
            - '80:80'
        environment:
#           predefined APP_KEY for faster testing
            APP_KEY: "base64:1NnEuFOXiJ08cgpqHi9WZnqbpLtrHvVeQCs0OP4UYwA="
            DB_CONNECTION: mysql
            DB_HOST: mariadb
            DB_PORT: 3306
            DB_DATABASE: fluffy_octo_fortnight
            DB_USERNAME: root
            DB_PASSWORD: password
        networks:
            - internal
        depends_on:
            - mariadb
    mariadb:
        image: 'mariadb:10'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'fluffy_octo_fortnight'
        volumes:
            - 'mariadb-database:/var/lib/mysql'
        networks:
            - internal
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    internal:
        driver: bridge

volumes:
    mariadb-database:
        driver: local
